name: Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Prepare
      run: npm ci
    - name: Check prettier
      run: npm run prettier-check
    - name: Check barrel files
      run: |
        npm run barrels
        npm run prettier
        git add -A
        git diff-index --quiet HEAD
