name: Generate documentation

on:
  push:
    branches:
      - master

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

      - name: Generate README
        run: npm run readme
      - name: Generate Typedoc
        run: npm run typedoc

  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

      - name: Generate demo output
        run: |
          npm run build
          cd demo
          npm ci
          npm run start ${{ secrets.MXUSERNAME }} ${{ secrets.MXAPIKEY }}

  commit:
    runs-on: ubuntu-latest
    needs: [readme, demo]
    steps:
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "[BUILD] Update README"
      - name: Push changes
        uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
